////////////////////////////////////////////
//
////////////////////////////////////////////
/////////////////////////////////////
//     Play A Guessing Game      ///
///////////////////////////////////
// program where the user has to guess a number generated by a program

var randNum = Math.floor( 10*Math.random() ) +1;
//var guess; 
function playTheGame(){ 
    let user = confirm("do you want to play");
    if(user){
        var guess =prompt( " enter number betwen 0 to 10 ");
    }else{
        alert("no problem goodbye");
    }

    function test(){
    	if(isNaN(guess)){
            alert("You did not guess a number!");  
        }
        else if(guess == randNum){
            alert(guess + " was the right number! It only took you " );
        }
        else if(guess >10|| guess<0){
            alert(` Sorry ${guess} it’s not a good number, Goodbye`);
        }
        else if (guess<randNum){
        	alert(`${guess} ist too low`);
        }
        else if (guess>randNum){
        	alert(`${guess} it is too highe `)
        }
    }
    test();

}
//playTheGame();

